#!/bin/sh
#
# Start test sequence
#

INTERFACE=eth0
REMOTE_IP=192.168.1.100

MMC_DEV=/dev/mmcblk0p1
MMC_MNT=/mnt

network_test() {
	ret=0
	# 1. test if network interface is present and UP.
	res=$(/sbin/ifconfig $INTERFACE | grep "UP")
	if [[ "x${res}x" == "xx" ]]; then
		ret=1
	else
		ping -c 2 $REMOTE_IP > /dev/null 2>&1
		ret=$?
	fi

	echo -n "Network Test: "
	if [[ $ret == 0 ]]; then
		echo "OK"
	else
		echo "KO"
	fi
	return $ret
}

sdcard_test() {
	ret=0
	# 1. test if mmc is present.
	res=$(ls $MMC_DEV 2>/dev/null)
	if [ ! -e $MMC_DEV ]; then
		echo "MMC Test: KO"
		return 1
	fi

	# 2. try to mount device
	mount $MMC_DEV $MMC_MNT > /dev/null 2>&1
	ret=$?
	if [[ $ret == 0 ]]; then
		# 3. try to read and compare file content
		ret=1
		content=$(cat $MMC_MNT/litex_ci.txt)
		if [[ "$content" == "Hello World" ]]; then
			ret=0
		fi

		umount $MMC_MNT > /dev/null 2>&1
	fi

	echo -n "MMC Test: "
	if [[ $ret == 0 ]]; then
		echo "OK"
	else
		echo "KO"
	fi

	return $ret
}


case "$1" in
	start)
		network_test
		sdcard_test
		;;
	*);;
esac
