#!/bin/sh
#
# LiteX HW CI Peripherals Test
#

# Configuration parameters.
INTERFACE=eth0
MMC_DEV=/dev/mmcblk0p1
USB_DEV=/dev/sda1
MOUNT_POINT=/mnt

# Result Helper.
echo_result() {
    echo -n "$1 Test: "
    [ $2 -eq 0 ] && echo "OK" || echo "KO"
}

# Network Test: Verify status and perform connectivity test.
network_test() {
    ifconfig $INTERFACE | grep -q "UP"
    if_up=$?

    ping -c 2 $(route | grep '^default' | awk '{print $2}') > /dev/null 2>&1
    ping_success=$?

    if [ $if_up -eq 0 ] && [ $ping_success -eq 0 ]; then
        echo_result Network 0
    else
        echo_result Network 1
    fi
}

# Storage Test: Verify file present, content of a storage device.
storage_test() {
    local DEVICE=$1
    local MOUNT=$2
    if [ -e $DEVICE ]; then
        mount $DEVICE $MOUNT > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            content=$(cat $MOUNT/litex_ci.txt 2>/dev/null)
            umount $MOUNT > /dev/null 2>&1
            [ "$content" == "Hello World" ] && return 0
        fi
    fi
    return 1
}

# SDCard Test.
sdcard_test() {
    if storage_test $MMC_DEV $MOUNT_POINT; then
        echo_result MMC 0
    else
        echo_result MMC 1
    fi
}

# USB Test.
usbhost_test() {
    if storage_test $USB_DEV $MOUNT_POINT; then
        echo_result USB 0
    else
        echo_result USB 1
    fi
}

# Run tests.
case "$1" in
    start)
        network_test
        sdcard_test
        usbhost_test
        ;;
esac
